### PR TITLE
Building with Responsive Design-Project

### PR DESCRIPTION
**Pull request by Samitti**
This project is the clone of thenextweb.com, the aim of the project was to build a responsive webpage.
We have validated for HTML and enabled linter.

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @Samitti  & @evabanegacom  :wave:
---
Your work is impressive guys! Nice job implementing the responsiveness of your site. :tada: There are, however, some minor changes we should do before we proceed (see review comment).
-
***Please make the changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.*** :eyes:
- Page Structure:
> Latest news section & Latest deals.
1. I noticed that the breakpoints at { (1174 x 922) to (1050 x 922) } is not as responsive as should be expected. We have a whole white (space) section that goes unfilled during this changeover. Rectify that.
> Article:
2. The articles appear too widely stretched, widthwise than normal. Rectify that.

- When you have made the specified changes, please submit another code review. Thank you!

*Happy coding :smile:*
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by Samitti** [comment]
We have fixed the problems in sections Latest news  & Latest deals.

**Comment by adaorachi** [comment]
👋 Hi @Samitti and @evabanegacom . Good job attempting the changes required but there are a few things you still need to fix on **responsiveness** to make your site look better, very professional and just like the original [thenextweb](https://thenextweb.com/). 
So hang in there, we've got your back! 💪 🌟 

### **CHANGES REQUIRED**

- Your site still has this overflowing white space running down the entire page of your site. And this seems to be very visible on medium and small breakpoints. Your site **should not** have the overflow scroll bar highlighted in the image below. So, look for that element causing the overflow and fix it. Make sure all sections of the site are well-aligned at the center of the page in every breakpoint with no trailing spaces by the sides.

**Your version:**
image111

**Original version:**
image11

---
- **The issue above can also be detected in this section too. Make sure to fix that.**
***

**Your version:**
image222

**Original Version:**
image22

---
- **The links in the footer are all squashed up. Make sure to fix that by making them properly spaced in between.**
***

**Your version:**
image4

**Original version:**
image44

---
- **Fix your navbar to have the highest stack order with z-index. Other sections of the page should not be visible on the navbar when scrolling. This is particularly noticed on medium and small breakpoints.**
***

image3
 
---
- **Your footer should contain a TNW logo, preferably an image but you have it as a text. Kindly fix this.**
***

image5
 
---
After implementing all the changes specified above, please request for another review by submitting a code review form.
Good-luck on it! 🤞 👍 

Should you have any questions or need help, please feel free to reach out to me on Slack with the handle (@adaorachi). ☺️ 

**MaryAnn Chukwuka.**

**Comment by evabanegacom** [comment]
I have fixed the errors

**Review by men32z — CHANGES_REQUESTED** [review]
You did great fixing the problems but still one missing   as you can se the styles in the footer aren't working, kindly fix this and send another review request. feel free to reach me on slack if you have questions



- Luis Preza

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Great job on this Team 👏👏👏

You've done quite well on this project.  👌

However, there still remain issues left to be fixed
Hang in there, you've got this👍

Kindly fix these issues: 

- [ ] Required - Like one of the reviews stated there still remains the issue of responsiveness to fix. A scrollbar is still visible on the x-axis on Tablet screen sizes. Kindly fix this issue. Refer to screenshots provided earlier.

- [ ] Required - Issues like the right color property to set shouldn't be overlooked in a project. There are three sections with the wrong color property:

### THIS IS THE FIRST SECTION:
**This section with the subheading `Latest News`, has the wrong color:[Screenshot] THIS IS YOURS👇** 
ice_screenshot_20200326-235319

**THIS IS THE WAY IT'S SUPPOSED TO LOOK [Screenshot]👇**
ice_screenshot_20200326-235356

### THIS IS THE SECOND SECTION:
**The footer has the wrong color property also. This is yours👇[Screenshot]**
ice_screenshot_20200327-001007

**THIS IS THE WAY IT'S SUPPOSED TO LOOK [Screenshot]👇**
ice_screenshot_20200327-001024

### THIS IS THE THIRD SECTION:
**This section with the heading `Latest Funding rounds`, has the wrong color also:[Screenshot] THIS IS YOURS👇** 
ice_screenshot_20200326-234839

**THIS IS THE WAY IT'S SUPPOSED TO LOOK [Screenshot]👇**
ice_screenshot_20200327-005529

Kindly fix these color issues.

- [ ] Required - In the top 3 article section at a Tablet screen size not only does the TNW logo disappear but the gradient also disappears with it. Make the gradient disappear on Tablet screen size

**This is yours 👇[Screenshot]**
ice_screenshot_20200327-000511

**This is the way it's supposed to be👇[Screenshot]**
ice_screenshot_20200327-000523

- [ ] Required - Also notice in the first screenshot above that on a tablet screen size, if you observe the top 3 articles section. The title of the article to the left is almost in the middle of the image, but it's supposed to be at the bottom level of the image.  Kindly fix this.

- [ ] Required - Also use an HTML validator tool to validate your HTML as there exists an error on your HTML file. Here is the [link](https://validator.w3.org/nu/).

- [ ] Required - Also increase the height of the same top 3 articles section.

- [ ] Required - Remove comments in your HTML file also if you want to review a previous version of your code use git history.


Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by sumancrest0001** [comment]
**This project is under review. Please keep patience.**  :pray: :pray: :pray:

**Comment by sumancrest0001** [comment]
[**REQUIRED CHANGES !!]** Awesome work TEAM @Samitti & @evabanegacom. It looks very good to me but we need to make a couple of changes to get green signal. Please make following changes.
:point_down: :point_down: :point_down:

**Comment by sumancrest0001** [comment]
In the mobile view title of the fist article is starts from middle. But it should start from bottom-left. 
**Your work**
Screenshot from 2020-03-27 11-45-13
It should be like this :point_down: :point_down:
Screenshot from 2020-03-27 11-45-38

**Comment by evabanegacom** [comment]
What changes

On Friday, 27 March 2020, Sman Shrestha <notifications@github.com> wrote:
> [REQUIRED CHANGES !!] Awesome work TEAM @Samitti & @evabanegacom. It
looks very good to me but we need to make a couple of changes to get green
signal. Please make following changes.
> 👇 👇 👇
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/YBypx2-8aeFib3tF2DEF-NAi5uKyRWI8guXlkiovduCyg3CqeWxsZlHgAE3KL1g5OqUqD137lYtW2w84GNmD47UJ345oK_eG2X3gzfDLAyK3dXDi2X_uo5ea2Ghqt4RbVtI3h2bRAS86vCZ5h3dTrH167ZYB-rnsqzoRRqaTTHj2XydGsCSH9P_vsoKYrYe3fYnor_xXHbZfgg_M7mpulr7t5uh_CcMe2NHlkhlLtw=s0-d-e1-ft#https://github.com/notifications/beacon/AOA7V3QRTBUYB7RCF2IOKGDRJQ7H5A5CNFSM4LUB2WK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEQGQEQQ.gif>

**Comment by sumancrest0001** [comment]
You need to give some margin between two elements.
In your project :point_down: :point_down:
Screenshot from 2020-03-27 11-42-23
It needs to be
Screenshot from 2020-03-27 11-42-53

**Comment by sumancrest0001** [comment]
Please validate the HTML. There is still one warning. :point_down: :point_down:
Screenshot from 2020-03-27 11-46-39

**Comment by sumancrest0001** [comment]
If you need any help, please contact me on slack [@suman](https://app.slack.com/client/T47CT8XPG/DL60H06RJ).
All the best :thumbsup: :thumbsup:

**Comment by sumancrest0001** [comment]
The title of the first article in mobile view starts from middle in you project but It should start from button left. Please have a look.
Screenshot from 2020-03-27 11-45-13
Screenshot from 2020-03-27 11-45-38

Sorry for the incomplete comment.

**Comment by lekegitrepo** [comment]
### Hi Team 👏 👏 
### Well done, the page looks great and the project is approved.

### Note: This is not mentioned in the previous review: the TNW logo should only move to the top left corner of the page when the screen size is 768px and less.

### add a margin between these contents:

tnwmargin

### Reviewed by: Temitayo Adeleke

-   Github: [@lekegitrepo](https://github.com/lekegitrepo)
-   Twitter: [@leketemi](https://twitter.com/leketemi)
-   Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — APPROVED** [review]
### Status: Approved

**Comment by evabanegacom** [comment]
heey, bro  it's time for the bootstrap

**Comment by evabanegacom** [comment]
I have fixed the errors

**Pull request merged**
